<?php
return array (
  'site_name' => '微信营销平台',
  'site_title' => '微信营销平台',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://localhost/jiada',
  'site_twm' => '',
  'site_my' => '微信',
  'server_key' => '123',
  'liaotian_key' => '123',
  'appid' => '',
  'secret' => '',
  'server_topdomain' => '',
  'connectout' => '已超出限制',
  'ischeckuser' => 'false',
  'reg_needmp' => 'false',
  'open_biz' => '0',
  'isclosekuser' => 'false',
  'demo' => 'true',
  'reg_groupid' => '4',
  'reg_validdays' => '1000',
  'router_key' => '',
  'ipc' => '京 ICP备',
  'site_qq' => '',
  'site_mp' => '4000000000',
  'baidu_map_api' => '2b79c282b0f365ca9782cceb499e6022',
  'site_email' => '',
  'keyword' => '',
  'content' => '',
  'countsz' => '',
  'copyright' => 'Copyright (c) 2015 版权所有',
  'close_help' => '0',
);
?>